import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync } from 'node:fs';
import BillingPanel from '../components/BillingPanel';
import ReportExport from '../components/ReportExport';
import { billingRequest } from '../services/billingClient';
import { registerPush } from '../services/native';
const memory = new Map<string,string>();
Object.assign(globalThis, { localStorage: { getItem: (k: string) => memory.get(k) ?? null, setItem: (k: string,v: string) => memory.set(k,v) }, window: { Capacitor: { isNativePlatform: () => true, getPlatform: () => 'ios' } } });
const billing = renderToStaticMarkup(<BillingPanel />);
assert.match(billing, /iOS/);
assert.doesNotMatch(billing, /二维码|微信购买|支付宝|Buy Pro/);
const report = renderToStaticMarkup(<ReportExport report={{title:'Example',abstract:'',sections:[],conclusions:[],openQuestions:[],references:[]}} />);
assert.doesNotMatch(report, /<button|微信|支付宝/);
await assert.rejects(billingRequest('/billing/orders', 'POST', {}), /iOS/);
assert.equal(await registerPush(() => { throw Error('unconfigured push must not register'); }), false);
const config = JSON.parse(readFileSync('ios/App/App/capacitor.config.json','utf8'));
assert.equal(config.appId,'com.hiexplore.app');
assert.equal(config.server?.url,undefined);
assert.equal(config.server?.cleartext,false);
assert.equal(config.plugins.CapacitorHttp.enabled,true);
assert.equal(config.webDir,'dist-ios');
console.log('iOS: local assets, HTTPS configuration, purchase guards, and honest push availability passed.');
