import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import assert from 'node:assert/strict';
import ProjectBrief from '../components/ProjectBrief';
import { loopFixture } from './exploration-loop.fixture';
import { recordJudgments, collectWaits } from '../services/problemHeartbeat';
import { reviewFact } from '../services/inquiry';
const noop = () => {};
const render = (project: any, state: any, connected = true, scopeId = 'root') => renderToStaticMarkup(<ProjectBrief project={project} scopeId={scopeId} state={state} connected={connected} onFacts={noop} onReview={noop} onSettings={noop} onTeam={noop} />);
let { project, state } = loopFixture();
state = recordJudgments(state, [{ subject: '降温方案', after: '先验证外遮阳', reason: '西窗受到直晒', evidenceIds: [state.context.facts[0].id] }], 'cloud1', Date.now(), () => 'judgment');
state.problemHeartbeat!.judgments[0].status = 'accepted';
let html = render(project, state);
assert.match(html, /先验证外遮阳/); assert.match(html, /核对依据 1 条/);
const revoked = structuredClone(project); revoked.inquiries!.root = reviewFact(revoked.inquiries!.root, state.context.facts[0].id, 'disputed', '需要重新测量');
html = render(revoked, state);
assert.match(html, /依据已变化/); assert.doesNotMatch(html, /先验证外遮阳/);
assert.match(render(project, state, false), /状态待确认/);
assert.doesNotMatch(render(project, state, true, 'shade'), /先验证外遮阳/);
const foreign = structuredClone(state); foreign.context.branchId = 'other';
assert.doesNotMatch(render(project, foreign), /先验证外遮阳/);
state = collectWaits(state, [{ kind: 'decision', title: '确认对照测量方案', detail: '是否按相同时间测量', owner: '用户', source: '实验计划', condition: '确认后继续' }], Date.now(), () => 'wait');
assert.match(render(project, state), /确认对照测量方案/);
const clean = loopFixture(); clean.state.status = 'sleeping'; clean.state.runs = [];
assert.doesNotMatch(render(clean.project, clean.state), /aria-label="需要你"/);
assert.match(render(clean.project, clean.state), /尚未形成已采纳判断/);
const storage = new Map(); (globalThis as any).localStorage = { getItem: (key: string) => storage.get(key), setItem: (key: string, val: string) => storage.set(key, val) };
storage.set('hiexplore-language', 'en');
assert.match(render(clean.project, clean.state), /Current understanding/);
console.log('Project brief: evidence withdrawal, source links, scope and branch isolation, offline state, action priority, quiet state and English passed.');
