import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import { canonical, mergeWorkspace, resolveSync, loadWorkspace, saveWorkspace, acknowledgeSync, syncSettings, backupWorkspace, restoreWorkspaceBackup } from '../services/projectSync';
import type { Project } from '../types';
Object.defineProperty(globalThis, 'crypto', { value: webcrypto });
const store = new Map<string, string>();
Object.defineProperty(globalThis, 'localStorage', { value: { getItem: (k: string) => store.get(k) || null, setItem: (k: string, v: string) => store.set(k, v), removeItem: (k: string) => store.delete(k) } });
const p = (id: string, name = id) => ({ id, name, metaProblem: id, nodes: [], createdAt: 1 } as Project);
const base = async (ps: Project[]) => Object.fromEntries(await Promise.all(ps.map(async p => [p.id, Buffer.from(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(canonical(p)))).toString('hex')])));
assert.deepEqual((await mergeWorkspace({}, [], [p('web')])).projects, [p('web')]);
assert.deepEqual((await mergeWorkspace({}, [p('phone')], [p('web')])).projects, [p('phone'), p('web')]);
assert.deepEqual((await mergeWorkspace(await base([p('a'), p('b')]), [p('a', 'local'), p('b')], [p('a'), p('b', 'cloud')])).projects, [p('a', 'local'), p('b', 'cloud')]);
assert.deepEqual((await mergeWorkspace(await base([p('a')]), [p('a')], [])).projects, []);
assert.deepEqual((await mergeWorkspace(await base([p('a')]), [], [p('a')])).projects, []);
const conflict = await mergeWorkspace(await base([p('a')]), [], [p('a', 'changed')]);
assert.deepEqual(conflict.conflicts, ['a']);
const plan = { ...conflict, local: [], localDigest: '[]', remote: { revision: 2, projects: [p('a', 'changed')], updatedAt: 1 } };
assert.throws(() => resolveSync(plan, {}));
assert.deepEqual(resolveSync(plan, { a: 'local' }), []);
assert.deepEqual(resolveSync(plan, { a: 'cloud' }), [p('a', 'changed')]);
assert.equal(canonical({ b: 1, apiKey: 'key', a: { credentialId: 'local', name: 'agent' } }), canonical({ a: { name: 'agent' }, b: 1 }));
store.set('exploration_projects_alice', JSON.stringify([p('old')]));
assert.deepEqual(await loadWorkspace('alice'), [p('old')]);
assert.equal(syncSettings('alice').enabled, false);
await acknowledgeSync('alice', { revision: 1, projects: [p('old')], updatedAt: 1 }, [p('old')]);
await saveWorkspace('alice', [p('old', 'edited')]);
await backupWorkspace('alice', [p('old', 'edited')]);
assert.equal(syncSettings('alice').enabled, true);
assert.deepEqual(await loadWorkspace('bob'), []);
await saveWorkspace('bob', [p('bob')]);
assert.deepEqual(await loadWorkspace('alice'), [p('old', 'edited')]);
await saveWorkspace('alice', []);
assert.deepEqual(await loadWorkspace('alice'), []);
await restoreWorkspaceBackup('alice');
assert.deepEqual(await loadWorkspace('alice'), [p('old', 'edited')]);
assert.equal(syncSettings('alice').enabled, false);
assert.deepEqual(await loadWorkspace('bob'), [p('bob')]);
console.log('Project sync merge, deletion conflicts, credential filtering, migration and account isolation passed');
